### ISSUE TITLE
Question re monitoring Github

### ISSUE THREAD

**Issue by Paul-Reed** [rsmmr/git-notifier#13]
Hi, can I ask please. do I just need the **github-notifier** script to monitor a github repo for changes, instead of installing the rest of your repo files (plus of course a cfg file).  I see that there is a **github-notifier.1** script, does that need to be included?  
I presume **Sendmail** is needed, are there any other pre-requisites.  
Thanks  
Paul

**Comment by rsmmr** [comment]
As a mininum, you need git-notifier and github-notifier both installed
into the same directory; plus the github-notifier.cfg configuration
file.

The other files aren't necessary for running the script
("github-notifier.1" is just documentation.)

Robin

## 

Robin Sommer \* ICSI/LBNL \* robin@icir.org \* www.icir.org/robin

**Comment by Paul-Reed** [comment]
Thanks Robert, I'll try and install it this evening. I can't believe github
doesn't send notifications as part of its core functionality.
