### ISSUE TITLE
--find-copies-harder confuses similar files

### ISSUE THREAD

**Issue by yeled** [rsmmr/git-notifier#15]
I use `git-notifier` to send my network device diffs to a mailing list. Many switches for instance may have the same config, except hostname and the salt of a password. With `--find-copies-harder` the diffs get confused, and every `git-notifier` run we get a diff of what looks like a switch changing it's hostname, but of course the file is the same.

Suggested feature request: create a `--not-so-hard` argv to disable this baked in command line 😃

**Comment by yeled** [comment]
example false-diff is:

```
@@ -48,7 +48,7 @@ groups {
 }
 /* Managed by CorpEng Ansible */
 system {
-    host-name chiwrt2;
+    host-name dubwrt2;
     ##
     ## Warning: statement ignored: unsupported platform (mx5-t)
     ##
@@ -63,13 +63,13 @@ system {
             secret "$9$.56Ap8wYgajH"; ## SECRET-DATA
             timeout 5;
             single-connection;
-            source-address 10.246.254.12;
+            source-address 10.248.254.12;
         }
         10.201.32.10 {
             secret "$9$-xwaUjAEcyeLx"; ## SECRET-DATA
             timeout 5;
             single-connection;
-            source-address 10.246.254.12;
+            source-address 10.248.254.12;
         }
     }
```

**Comment by rsmmr** [comment]
I've just removed that option altogether, should be just fine without it.
