### ISSUE TITLE
Missing notifications about lightweight tags

### ISSUE THREAD

**Issue by rob006** [rsmmr/git-notifier#20]
When you create lightweight tag in this way:

```console
git tag v1.0.0
```

no notifications are send. 

https://git-scm.com/book/en/v2/Git-Basics-Tagging#_lightweight_tags

**Comment by rob006** [comment]
It looks like this behavior is intentional: https://github.com/rsmmr/git-notifier/blob/5bef07a11514df1be5e977aa966bc6bd14a5ba0d/git-notifier#L331

But why we ignoring lightweight tags?

**Comment by rsmmr** [comment]
I don't quite remember the specifics but I think it was because the lightweight tags don't come with the meta data for generating the notifications (i.e, author, message). For them notifications would pull the data from the commit itself, which doesn't seem right.

**Comment by rob006** [comment]
This is exactly the same situation as with new branches (which have notifications). You do not need extra meta data, simple information that there is new tag is enought and still very useful. Currently I'm using a patched version of git-notifier that sends notifications about lightweight tags, because some projects on GitHub uses lightewight tags and github-notifier just ignores them (so you won't get notifications about new releases!).
