### ISSUE TITLE
Exception when commit author contains non-latin1 characters

### ISSUE THREAD

**Issue by 0xabadea** [rsmmr/git-notifier#4]
A co-worker is called Ondřej (that's like Andrew in Czech). git-notifier threw an exception when sending his first commit. I don't have the stack trace anymore, but it was on this line in encodeHeader():

hdr = hdr.decode('utf-8').encode('latin1')

I fixed this by setting mimify's default charset to UTF-8. I will send a pull request.

**Comment by rsmmr** [comment]
Merge the corresponding pull request.
