### ISSUE TITLE
Non-ascii characters in body are not transferred correctly

### ISSUE THREAD

**Issue by 0xabadea** [rsmmr/git-notifier#6]
Some files in our repo contain UTF-8 encoded non-ASCII characters, such as "ěščřžýáíé". In diffs sent by git-notifier, this string looks like:

diff --git a/file b/file
new file mode 100644
index 0000000..8874d5e
--- /dev/null
+++ b/file
@@ -0,0 +1 @@
+Ä›Å¡ÄÅ™Å¾Ã½Ã¡Ã­Ã©

The reason seems to be the UTF-8 content is not marked as such via a Content-Type header, and also, 8bit content seems to be better transferred as quoted-printable.

**Comment by rsmmr** [comment]
Merge the corresponding pull request.
